apiVersion: v2
name: go-app
description: A Helm chart for Kubernetes

type: application

version: 1.0.0

appVersion: "1.0.0"

dependencies:
  - name: redis
    version: 19.0.1
    repository: https://charts.bitnami.com/bitnami
