replicaCount: 1

image:
  repository: devops_test_go-go-app
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 8080

ingress: # to do: configure ingress
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: go-app.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80


volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

redisAddress: "go-app-redis-master.default.svc.cluster.local:6379" # to do: remove hardcode

redis:
  architecture: standalone
  auth:
    enabled: false
